export const tagTypes = [
  "User",
  "Product",
  "Products",
  "Categories",
  "Reviews",
  "Cart",
  "Addresses",
  "CustomerOrders",
  "AdminProducts",
  "AdminVariants",
  "AdminImages",
  "AdminReviews",
  "AdminUsers",
  "AdminPages",
  "AdminOrders",
  "AdminPayments",
  "AdminAnalytics",
  "SiteSettings",
  "PaymentSettings",
  "OrderSettings",
] as const;
export type TagTypes = (typeof tagTypes)[number];
